const dados = [
  {
    rating: 91,
    position: "ATA",
    name: "Mbappé",
    fullName: "Kylian Mbappé",
    image: "public/imgs/players/mbappe.png",
    type: "gold",
    stats: {
      pace: 97,
      shooting: 91,
      passing: 81,
      dribbling: 92,
      defense: 40,
      physical: 81,
    },
  },
  {
    rating: 93,
    position: "SA",
    name: "Cruyff",
    fullName: "Johan Cruiff",
    image: "public/imgs/players/cruyff.png",
    type: "icon",
    stats: {
      pace: 91,
      shooting: 93,
      passing: 83,
      dribbling: 92,
      defense: 40,
      physical: 87,
    },
  },
  {
    rating: 91,
    position: "MEI",
    name: "Zico",
    fullName: "Arthur Antunes Coimbra Zico",
    image: "public/imgs/players/zico.png",
    type: "icon",
    stats: {
      pace: 89,
      shooting: 92,
      passing: 91,
      dribbling: 91,
      defense: 62,
      physical: 71,
    },
  },
  {
    rating: 90,
    position: "SA",
    name: "Kerr",
    fullName: "Sam Kerr",
    image: "public/imgs/players/kerr.png",
    type: "gold",
    stats: {
      pace: 85,
      shooting: 88,
      passing: 74,
      dribbling: 90,
      defense: 42,
      physical: 85,
    },
  },
  {
    rating: 90,
    position: "MC",
    name: "Aitana",
    fullName: "Aitana Bonmati",
    image: "public/imgs/players/bonmati.png",
    type: "gold",
    stats: {
      pace: 81,
      shooting: 84,
      passing: 83,
      dribbling: 91,
      defense: 75,
      physical: 73,
    },
  },
  {
    rating: 90,
    position: "MC",
    name: "De Bruyne",
    fullName: "Kevin De Bruyne",
    image: "public/imgs/players/debruyne.png",
    type: "gold",
    stats: {
      pace: 74,
      shooting: 86,
      passing: 91,
      dribbling: 87,
      defense: 64,
      physical: 78,
    },
  },
  {
    rating: 88,
    position: "ATA",
    name: "Ronaldo",
    fullName: "Cristiano Ronaldo",
    image: "public/imgs/players/cristianoronaldo.png",
    type: "gold",
    stats: {
      pace: 78,
      shooting: 90,
      passing: 79,
      dribbling: 85,
      defense: 42,
      physical: 82,
    },
  },
  {
    rating: 87,
    position: "PE",
    name: "Neymar",
    fullName: "Neymar Júnior",
    image: "public/imgs/players/neymar.png",
    type: "gold",
    stats: {
      pace: 88,
      shooting: 83,
      passing: 86,
      dribbling: 91,
      defense: 37,
      physical: 59,
    },
  },
  {
    rating: 88,
    position: "MEI",
    name: "Messi",
    fullName: "Lionel Messi",
    image: "public/imgs/players/messi.png",
    type: "gold",
    stats: {
      pace: 84,
      shooting: 88,
      passing: 87,
      dribbling: 90,
      defense: 34,
      physical: 60,
    },
  },
  {
    rating: 83,
    position: "MEI",
    name: "Dani Olmo",
    fullName: "Daniel Olmo Carvajal",
    image: "public/imgs/players/daniolmo.png",
    type: "gold",
    stats: {
      pace: 72,
      shooting: 80,
      passing: 82,
      dribbling: 84,
      defense: 40,
      physical: 74,
    },
  },
  {
    rating: 89,
    position: "ZAG",
    name: "Van Dijk",
    fullName: "Virgil van Dijk",
    image: "public/imgs/players/vandijk.png",
    type: "gold",
    stats: {
      pace: 80,
      shooting: 50,
      passing: 72,
      dribbling: 70,
      defense: 90,
      physical: 92,
    },
  },
  {
    rating: 91,
    position: "ATA",
    name: "Haaland",
    fullName: "Erling Haaland",
    image: "public/imgs/players/haaland.png",
    type: "gold",
    stats: {
      pace: 89,
      shooting: 90,
      passing: 70,
      dribbling: 84,
      defense: 40,
      physical: 90,
    },
  },
  {
    rating: 86,
    position: "ZAG",
    name: "Ramos",
    fullName: "Sergio Ramos",
    image: "public/imgs/players/ramos.png",
    type: "gold",
    stats: {
      pace: 72,
      shooting: 55,
      passing: 70,
      dribbling: 65,
      defense: 90,
      physical: 88,
    },
  },
  {
    rating: 84,
    position: "LE",
    name: "Davies",
    fullName: "Alphonso Davies",
    image: "public/imgs/players/davies.png",
    type: "gold",
    stats: {
      pace: 92,
      shooting: 70,
      passing: 75,
      dribbling: 85,
      defense: 80,
      physical: 78,
    },
  },
  {
    rating: 87,
    position: "MEI",
    name: "Modrić",
    fullName: "Luka Modrić",
    image: "public/imgs/players/modric.png",
    type: "gold",
    stats: {
      pace: 70,
      shooting: 83,
      passing: 90,
      dribbling: 86,
      defense: 80,
      physical: 75,
    },
  },
];
