const dados = [
  {
    rating: 91,
    position: "ATA",
    name: "Mbappé",
    fullName: "Kylian Mbappé",
    image: "public/imgs/players/mbappe.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/35/kylian-mbappe",
    stats: {
      pace: 97,
      shooting: 91,
      passing: 81,
      dribbling: 92,
      defense: 40,
      physical: 81,
    },
  },
  {
    rating: 93,
    position: "SA",
    name: "Cruyff",
    fullName: "Johan Cruiff",
    image: "public/imgs/players/cruyff.webp",
    type: "icon",
    url: "https://www.futbin.com/24/player/18987/johan-cruyff",
    stats: {
      pace: 91,
      shooting: 93,
      passing: 83,
      dribbling: 92,
      defense: 40,
      physical: 87,
    },
  },
  {
    rating: 91,
    position: "MEI",
    name: "Zico",
    fullName: "Arthur Antunes Coimbra Zico",
    image: "public/imgs/players/zico.webp",
    type: "icon",
    url: "https://www.futbin.com/24/player/18984/antunes-coimbra",
    stats: {
      pace: 89,
      shooting: 92,
      passing: 91,
      dribbling: 91,
      defense: 62,
      physical: 71,
    },
  },
  {
    rating: 90,
    position: "SA",
    name: "Kerr",
    fullName: "Sam Kerr",
    image: "public/imgs/players/kerr.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/32/sam-kerr",
    stats: {
      pace: 85,
      shooting: 88,
      passing: 74,
      dribbling: 90,
      defense: 42,
      physical: 85,
    },
  },
  {
    rating: 90,
    position: "MC",
    name: "Aitana",
    fullName: "Aitana Bonmati",
    image: "public/imgs/players/bonmati.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/38/aitana-bonmati-conca",
    stats: {
      pace: 81,
      shooting: 84,
      passing: 83,
      dribbling: 91,
      defense: 75,
      physical: 73,
    },
  },
  {
    rating: 91,
    position: "MC",
    name: "De Bruyne",
    fullName: "Kevin De Bruyne",
    image: "public/imgs/players/debruyne.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/37/kevin-de-bruyne",
    stats: {
      pace: 74,
      shooting: 86,
      passing: 91,
      dribbling: 87,
      defense: 64,
      physical: 78,
    },
  },
  {
    rating: 88,
    position: "ATA",
    name: "Ronaldo",
    fullName: "Cristiano Ronaldo",
    image: "public/imgs/players/cristianoronaldo.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/23090/cristiano-ronaldo",
    stats: {
      pace: 78,
      shooting: 90,
      passing: 79,
      dribbling: 85,
      defense: 42,
      physical: 82,
    },
  },
  {
    rating: 87,
    position: "PE",
    name: "Neymar",
    fullName: "Neymar Júnior",
    image: "public/imgs/players/neymar.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/50/neymar-jr",
    stats: {
      pace: 88,
      shooting: 83,
      passing: 86,
      dribbling: 91,
      defense: 37,
      physical: 59,
    },
  },
  {
    rating: 88,
    position: "MEI",
    name: "Messi",
    fullName: "Lionel Messi",
    image: "public/imgs/players/messi.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/39/lionel-messi",
    stats: {
      pace: 84,
      shooting: 88,
      passing: 87,
      dribbling: 90,
      defense: 34,
      physical: 60,
    },
  },
  {
    rating: 83,
    position: "MEI",
    name: "Dani Olmo",
    fullName: "Daniel Olmo Carvajal",
    image: "public/imgs/players/daniolmo.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/29711/dani-olmo",
    stats: {
      pace: 72,
      shooting: 80,
      passing: 82,
      dribbling: 84,
      defense: 40,
      physical: 74,
    },
  },
  {
    rating: 89,
    position: "ZAG",
    name: "Van Dijk",
    fullName: "Virgil van Dijk",
    image: "public/imgs/players/vandijk.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/28/virgil-van-dijk",
    stats: {
      pace: 80,
      shooting: 50,
      passing: 72,
      dribbling: 70,
      defense: 90,
      physical: 92,
    },
  },
  {
    rating: 91,
    position: "ATA",
    name: "Haaland",
    fullName: "Erling Haaland",
    image: "public/imgs/players/haaland.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/23/erling-haaland",
    stats: {
      pace: 89,
      shooting: 90,
      passing: 70,
      dribbling: 84,
      defense: 40,
      physical: 90,
    },
  },
  {
    rating: 87,
    position: "ZAG",
    name: "Ramos",
    fullName: "Sergio Ramos",
    image: "public/imgs/players/ramos.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/23098/ramos-garcia",
    stats: {
      pace: 72,
      shooting: 55,
      passing: 70,
      dribbling: 65,
      defense: 90,
      physical: 88,
    },
  },
  {
    rating: 84,
    position: "LE",
    name: "Davies",
    fullName: "Alphonso Davies",
    image: "public/imgs/players/davies.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/320/alphonso-davies",
    stats: {
      pace: 92,
      shooting: 70,
      passing: 75,
      dribbling: 85,
      defense: 80,
      physical: 78,
    },
  },
  {
    rating: 87,
    position: "MEI",
    name: "Modrić",
    fullName: "Luka Modrić",
    image: "public/imgs/players/modric.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/226/luka-modric",
    stats: {
      pace: 70,
      shooting: 83,
      passing: 90,
      dribbling: 86,
      defense: 80,
      physical: 75,
    },
  },
  {
    rating: 91,
    position: "MC",
    name: "Putellas",
    fullName: "Alexia Putellas Segura",
    image: "public/imgs/players/putellas.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/36/alexia-putellas-segura",
    stats: {
      pace: 78,
      shooting: 84,
      passing: 90,
      dribbling: 88,
      defense: 60,
      physical: 70,
    },
  },
  {
    rating: 87,
    position: "ZAG",
    name: "Marquinhos",
    fullName: "Marcos Aoás Corrêa",
    image: "public/imgs/players/marquinhos.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/412/marquinhos",
    stats: {
      pace: 75,
      shooting: 55,
      passing: 70,
      dribbling: 68,
      defense: 87,
      physical: 85,
    },
  },
  {
    rating: 84,
    position: "LD",
    name: "Hakimi",
    fullName: "Achraf Hakimi",
    image: "public/imgs/players/hakimi.webp",
    url: "https://www.futbin.com/24/player/411/achraf-hakimi",
    type: "gold",
    stats: {
      pace: 92,
      shooting: 68,
      passing: 75,
      dribbling: 82,
      defense: 78,
      physical: 82,
    },
  },
  {
    rating: 88,
    position: "MEI",
    name: "Fernandes",
    fullName: "Bruno Miguel Borges Fernandes",
    image: "public/imgs/players/fernandes.webp",
    type: "gold",
    url: "https://www.futbin.com/24/player/69/bruno-fernandes",
    stats: {
      pace: 75,
      shooting: 85,
      passing: 90,
      dribbling: 82,
      defense: 60,
      physical: 80,
    },
  },
  {
    rating: 99,
    position: "MEI",
    name: "Pelé",
    fullName: "Edson Arantes do Nascimento",
    image: "public/imgs/players/pele.webp",
    type: "icon",
    url: "https://www.futbin.com/24/player/27812/pele",
    stats: {
      pace: 95,
      shooting: 96,
      passing: 93,
      dribbling: 96,
      defense: 50,
      physical: 75,
    },
  },
  {
    rating: 94,
    position: "ATA",
    name: "Ronaldo",
    fullName: "Ronaldo Luís Nazário de Lima",
    image: "public/imgs/players/ronaldo.webp",
    url: "https://www.futbin.com/24/player/18980/ronaldo",
    type: "icon",
    stats: {
      pace: 94,
      shooting: 95,
      passing: 81,
      dribbling: 93,
      defense: 40,
      physical: 82,
    },
  },
  {
    rating: 93,
    position: "ZAG",
    name: "Maldini",
    fullName: "Paolo Maldini",
    image: "public/imgs/players/maldini.webp",
    type: "icon",
    url: "https://www.futbin.com/24/player/20439/paolo-maldini",
    stats: {
      pace: 86,
      shooting: 50,
      passing: 72,
      dribbling: 70,
      defense: 95,
      physical: 85,
    },
  },
  {
    rating: 94,
    position: "MEI",
    name: "Zidane",
    fullName: "Zinedine Zidane",
    image: "public/imgs/players/zidane.webp",
    url: "https://www.futbin.com/24/player/18913/zinedine-zidane",
    type: "icon",
    stats: {
      pace: 85,
      shooting: 90,
      passing: 94,
      dribbling: 92,
      defense: 60,
      physical: 78,
    },
  },
  {
    rating: 91,
    position: "MEI",
    name: "Hazard",
    fullName: "Eden Hazard",
    image: "public/imgs/players/hazard.webp",
    type: "hero",
    url: "https://www.futbin.com/25/player/10/eden-hazard",
    stats: {
      pace: 86,
      shooting: 85,
      passing: 86,
      dribbling: 90,
      defense: 40,
      physical: 70,
    },
  },
  {
    rating: 89,
    position: "ATA",
    name: "Forlán",
    fullName: "Diego Forlán",
    image: "public/imgs/players/forlan.webp",
    type: "hero",
    url: "https://www.futbin.com/24/player/20110/diego-forlan",
    stats: {
      pace: 85,
      shooting: 91,
      passing: 80,
      dribbling: 84,
      defense: 40,
      physical: 78,
    },
  },
  {
    rating: 89,
    position: "ZAG",
    name: "Lúcio",
    fullName: "Lucimar Ferreira da Silva",
    image: "public/imgs/players/lucio.webp",
    type: "hero",
    url: "https://www.futbin.com/24/player/19067/lucimar-da-silva-ferreira",
    stats: {
      pace: 82,
      shooting: 55,
      passing: 72,
      dribbling: 68,
      defense: 89,
      physical: 87,
    },
  },
  {
    rating: 87,
    position: "ATA",
    name: "Kuyt",
    fullName: "Dirk Kuyt",
    image: "public/imgs/players/kuyt.webp",
    type: "hero",
    url: "https://www.futbin.com/24/player/20106/dirk-kuyt",
    stats: {
      pace: 80,
      shooting: 84,
      passing: 82,
      dribbling: 83,
      defense: 50,
      physical: 85,
    },
  },
];
